version: '3.4'

services:
  healthtrackerapi:
    restart: always
    image: ${DOCKER_REGISTRY-}hectoritobonito/healthtrackerapi:latest
    build:
      context: .
      dockerfile: HealthTrackerAPI/Dockerfile
    ports:
    - 5432:80
    depends_on:
            - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password123."
        ACCEPT_EULA: "Y"